name: bwu_utils_server
version: 0.0.4+1
description: utils that depend on 'dart:io'
homepage: https://github.com/bwu-dart/bwu_utils_server
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  bwu_utils: '>=0.0.1 <0.1.0'
#    path: ../bwu_utils
  path: ^1.3.0

dev_dependencies:
  unittest: any
